### PR TITLE
Make zoom click through

### PR DESCRIPTION
**Pull request by manogi**
This makes it possible to click through the zoomed images (right half of the image forward - left half back).

### CODE REVIEW

**Comment by jackmcdade** [comment]
Very nice addition! Thank you!

**Comment by manogi** [comment]
CSS and JS assets would have to be republished (`npm run production`), because of some new tailwind classes!

**Comment by jackmcdade** [comment]
That's done on the deploy script, all good!

**Comment by manogi** [comment]
Cool, thanks for merging.

**Pull request merged**
